name: HOT-WebUI Action

on: workflow_dispatch

jobs:

  WEBUI-Action:
    runs-on: t2
    name: Execute Web-Ui Test
    steps:
      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: "C:/Data/zphyrscript/results/*.xml"
      
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
         path: artifacts
        
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
            files: "artifacts/**/*.xml"
          
          
