name: HOT-WebUI Action

on: workflow_dispatch

jobs:

  WEBUI-Action:
    runs-on: t2
    name: Execute Web-Ui Test
    steps:
      
      - name: Surefire Report
        uses: ScaCap/action-surefire-report@v1.0.5
        with:
          report_paths: "C:/Data/zphyrscript/results/*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
