name: HOT-WebUI Action

on: workflow_dispatch

jobs:

  WEBUI-Action:
    runs-on: t2
    name: Execute Web-Ui Test
    steps:
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
            files: "C:/Data/zphyrscript/results/*.xml"
          
          
