name: HOT-WebUI Action

on: workflow_dispatch

jobs:

  WEBUI-Action:
    runs-on: t2
    name: Execute Web-Ui Test
    steps:
      - name: Execute test
        uses: rathorpraveen/webui@main
        with:
          productpath: C:\Program Files\HCL\HCLOneTestfresh
          imshared: C:\Program Files\HCL\HCLIMShared  
          workspace: C:\Users\praveen.rathor\HCL\hclonetest\workspace\moeb
          project: demo
          suite: demo
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: "C:/Data/zphyrscript/results/*.xml"
          
          
