name: HOT-WebUI Action

on: workflow_dispatch

jobs:

  WEBUI-Action:
    runs-on: t2
    name: Execute Web-Ui Test
    steps:
      - name: Execute test
        uses: rathorpraveen/webui@main
        with:
          productpath: C:\Program Files\HCL\HCLOneTestfresh
          imshared: C:\Program Files\HCL\HCLIMShared  
          workspace: C:\Users\praveen.rathor\HCL\hclonetest\workspace\moeb
          project: demo
          suite: demo
      - name: Surefire Report
        uses: ScaCap/action-surefire-report@v1.0.5
        with:
          files: "C:/Data/zphyrscript/results/*.xml"
          
          
