
name: newpublisher Action

on: workflow_dispatch

jobs:

  WEBUI-Action:
    runs-on: t2
    name: publish junit Test
    steps:
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:  
          report_paths: 'C:/Data/zphyrscript/results/TEST-*.xml'
